name: comet
version: 0.0.1
description: A web irc client and a proxy irc websocket server.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  args: '>=0.12.0 <0.13.0'
  browser: any
  irc: '>=2.0.0'
  quiver: any
  shelf: '>=0.5.5 <0.6.0'
  shelf_route: any
  shelf_static: any
  shelf_web_socket: any
